### ISSUE TITLE
unknown keyword: :uses_transaction

### ISSUE THREAD

**Issue by andriesfilmer** [trilogy-libraries/activerecord-trilogy-adapter#75]
I like to switch from mysql2 to trylogy but if i add the "activerecord-trilogy-adapter" gem in my Gemfile and change the adaptor in my "config/database.yml" to trilogy i get the next error:

`unknown keyword: :uses_transaction`

```
      def call(env)
        env[Const::PUMA_CONFIG] = @config
        @app.call(env)
      end
    end

```

[Application Trace](http://crm.lvh.me:3000/crm#) | [Framework Trace](http://crm.lvh.me:3000/crm#) | [Full Trace](http://crm.lvh.me:3000/crm#)
[activerecord (7.1.4.1) lib/active_record/connection_adapters/abstract_adapter.rb:998:in `with_raw_connection'](http://crm.lvh.me:3000/crm#)
[activerecord-trilogy-adapter (2.2.0) lib/active_record/connection_adapters/trilogy_adapter.rb:210:in `get_full_version'](http://crm.lvh.me:3000/crm#)
[activerecord (7.1.4.1) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:87:in `get_database_version'](http://crm.lvh.me:3000/crm#)
[activerecord (7.1.4.1) lib/active_record/connection_adapters/schema_cache.rb:374:in `database_version'](http://crm.lvh.me:3000/crm#)

Any help I would greatly appreciate

**Comment by bensheldon** [comment]
If you're using Rails 7.1+, you don't need to use this gem and it should be removed from your gemfile; Rails 7.1+ itself includes a version of this adapter.

Duplicate of #68.

**Comment by andriesfilmer** [comment]
Hi bensheldon, thanks for you feedback. Indeed its mentioned that you don't need to install the gem "activerecord-trilogy-adapter" when using rails v7.1+. But when booting rails server i get the message:

```
rails s
=> Booting Puma
=> Rails 7.1.4.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
Exiting
/usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/rubygems_integration.rb:280:in `block (2 levels) in replace_gem': Error loading the 'trilogy' Active Record adapter. Missing a gem it depends on? trilogy is not part of the bundle. Add it to your Gemfile. (LoadError)

```
